-- Judgemind database schema (auto-generated).
-- DO NOT EDIT THIS FILE DIRECTLY.
-- To modify the schema, add a migration in packages/api/migrations/
-- then run: scripts/regenerate_schema.sh
--
-- Generated from 44 migrations.



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA derived;


CREATE SCHEMA dispatcher;


CREATE SCHEMA staging;


CREATE SCHEMA telemetry;


CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


CREATE TYPE public.alert_type AS ENUM (
    'case_docket',
    'judge_ruling',
    'keyword',
    'party_attorney'
);


CREATE TYPE public.document_format AS ENUM (
    'html',
    'pdf',
    'docx',
    'txt'
);


CREATE TYPE public.document_status AS ENUM (
    'active',
    'superseded',
    'removed'
);


CREATE TYPE public.ruling_outcome AS ENUM (
    'granted',
    'denied',
    'granted_in_part',
    'denied_in_part',
    'moot',
    'continued',
    'off_calendar',
    'submitted',
    'other'
);


CREATE TYPE public.validation_status AS ENUM (
    'pending',
    'passed',
    'failed',
    'flagged'
);


CREATE FUNCTION dispatcher.issue_cooldown_remaining_seconds(p_issue_number integer, p_cooldown_seconds integer) RETURNS integer
    LANGUAGE sql STABLE
    AS $$
    SELECT GREATEST(0,
        p_cooldown_seconds - EXTRACT(EPOCH FROM (now() - MAX(started_at)))::integer
    )
      FROM dispatcher.agents
     WHERE issue_number = p_issue_number
    HAVING MAX(started_at) IS NOT NULL;
$$;


COMMENT ON FUNCTION dispatcher.issue_cooldown_remaining_seconds(p_issue_number integer, p_cooldown_seconds integer) IS 'Returns the seconds remaining in the cooldown window keyed on MAX(started_at) for any prior agent row for this issue. NULL when there is no prior row (never attempted). 0 when cooldown has elapsed (GREATEST keeps it non-negative). Issue #3001.';


CREATE FUNCTION dispatcher.issue_has_active_agent(p_issue_number integer) RETURNS boolean
    LANGUAGE sql STABLE
    AS $$
    SELECT EXISTS (
        SELECT 1
          FROM dispatcher.agents
         WHERE issue_number = p_issue_number
           AND status IN ('running', 'retrying', 'succeeded', 'needs_review')
    );
$$;


COMMENT ON FUNCTION dispatcher.issue_has_active_agent(p_issue_number integer) IS 'Returns TRUE when dispatcher.agents has any row for this issue with status IN (''running'', ''retrying'', ''succeeded'', ''needs_review''). Mirrors ACTIVE_AGENT_STATUSES in scripts/dispatcher/daemon.py:354. Issue #3001.';


CREATE FUNCTION public.update_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


SET default_table_access_method = heap;

CREATE TABLE derived.attorney_aliases (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    attorney_id uuid NOT NULL,
    raw_name text NOT NULL,
    source text,
    confidence double precision,
    is_verified boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT attorney_aliases_confidence_check CHECK (((confidence >= (0)::double precision) AND (confidence <= (1)::double precision)))
);


CREATE TABLE derived.attorneys (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    canonical_name text NOT NULL,
    bar_number text,
    bar_state character(2),
    firm_name text,
    email text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


CREATE TABLE derived.case_attorneys (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    case_id uuid NOT NULL,
    attorney_id uuid NOT NULL,
    role text NOT NULL,
    party_id uuid,
    appeared_at date,
    withdrew_at date
);


CREATE TABLE derived.case_judges (
    case_id uuid NOT NULL,
    judge_id uuid NOT NULL,
    assigned_at date,
    is_current boolean DEFAULT true NOT NULL
);


CREATE TABLE derived.case_parties (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    case_id uuid NOT NULL,
    party_id uuid NOT NULL,
    role text NOT NULL
);


CREATE TABLE derived.cases (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    case_number text NOT NULL,
    case_number_normalized text,
    court_id uuid NOT NULL,
    case_type text,
    case_subtype text,
    case_status text,
    case_title text,
    filed_at date,
    closed_at date,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


CREATE TABLE derived.court_directory_snapshots (
    id integer NOT NULL,
    court_id text NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    s3_key text NOT NULL,
    mapping jsonb NOT NULL,
    content_hash text NOT NULL
);


CREATE SEQUENCE derived.court_directory_snapshots_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE derived.court_directory_snapshots_id_seq OWNED BY derived.court_directory_snapshots.id;


CREATE TABLE derived.courts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    state character varying(20) NOT NULL,
    county text NOT NULL,
    court_name text NOT NULL,
    court_code text NOT NULL,
    timezone text DEFAULT 'America/Los_Angeles'::text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    scraper_config jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


COMMENT ON TABLE derived.courts IS 'Reference table for jurisdictions. One row per court.';


COMMENT ON COLUMN derived.courts.court_code IS 'Slug used in S3 key paths: /{state}/{county}/{court}/...';


CREATE TABLE derived.documents (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    case_id uuid,
    court_id uuid NOT NULL,
    document_type text NOT NULL,
    motion_type text,
    s3_key text NOT NULL,
    s3_bucket text NOT NULL,
    format public.document_format NOT NULL,
    content_hash text NOT NULL,
    source_url text,
    scraper_id text,
    captured_at timestamp with time zone NOT NULL,
    hearing_date date,
    published_at timestamp with time zone,
    status public.document_status DEFAULT 'active'::public.document_status NOT NULL,
    previous_version_id uuid,
    change_type text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL
);


COMMENT ON COLUMN derived.documents.content_hash IS 'SHA-256. Used for dedup and to detect revisions across scraper runs.';


COMMENT ON COLUMN derived.documents.change_type IS 'LLM-classified when a new version is captured: substantive or cosmetic.';


CREATE TABLE derived.judge_aliases (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    judge_id uuid NOT NULL,
    raw_name text NOT NULL,
    source text,
    confidence double precision,
    is_verified boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT judge_aliases_confidence_check CHECK (((confidence >= (0)::double precision) AND (confidence <= (1)::double precision)))
);


CREATE TABLE derived.judges (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    canonical_name text NOT NULL,
    court_id uuid NOT NULL,
    department text,
    is_active boolean DEFAULT true NOT NULL,
    appointed_at date,
    biographical_notes text,
    bio_reviewed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


CREATE TABLE derived.parties (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    canonical_name text NOT NULL,
    party_type text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


CREATE TABLE derived.party_aliases (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    party_id uuid NOT NULL,
    raw_name text NOT NULL,
    source text,
    confidence double precision,
    is_verified boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT party_aliases_confidence_check CHECK (((confidence >= (0)::double precision) AND (confidence <= (1)::double precision)))
);


CREATE TABLE derived.rulings (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    document_id uuid NOT NULL,
    case_id uuid NOT NULL,
    judge_id uuid,
    court_id uuid NOT NULL,
    ruling_text text,
    ruling_text_html text,
    outcome public.ruling_outcome,
    motion_type text,
    hearing_date date,
    posted_at timestamp with time zone,
    summary text,
    summary_model text,
    summary_generated_at timestamp with time zone,
    department text,
    is_tentative boolean DEFAULT true NOT NULL,
    ruling_number integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    ruling_text_hash text
);


COMMENT ON COLUMN derived.rulings.judge_id IS 'Nullable: populated by entity resolution after initial capture.';


COMMENT ON COLUMN derived.rulings.summary IS 'Cached AI summary. Served from cache on every request.';


COMMENT ON COLUMN derived.rulings.ruling_text_hash IS 'SHA-256 of normalized (lowercased, whitespace-collapsed) ruling text. Used for content-based dedup.';


CREATE TABLE dispatcher.agents (
    agent_id uuid DEFAULT gen_random_uuid() NOT NULL,
    parent_run_id uuid,
    kind text DEFAULT 'task'::text NOT NULL,
    issue_number integer NOT NULL,
    worktree_path text NOT NULL,
    phase text DEFAULT 'claiming'::text NOT NULL,
    status text DEFAULT 'running'::text NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    ended_at timestamp with time zone,
    exit_code integer,
    pr_number integer,
    retries_used integer DEFAULT 0 NOT NULL,
    pid integer,
    runner_override jsonb,
    model_override jsonb,
    issue_title text,
    failure_summary text,
    priority text,
    merged_at timestamp with time zone,
    verified_at timestamp with time zone,
    verify_skip_reason text,
    retroed_at timestamp with time zone,
    agent_task_arn text,
    execution_mode text DEFAULT 'subprocess'::text NOT NULL,
    ralph_iterations_observed integer DEFAULT 0 NOT NULL,
    merge_unstick_attempts integer DEFAULT 0 NOT NULL,
    merge_conflict_attempts integer DEFAULT 0 NOT NULL
);


COMMENT ON TABLE dispatcher.agents IS 'One row per /task (or audit/spotcheck/security-review) agent invocation.';


COMMENT ON COLUMN dispatcher.agents.runner_override IS 'Per-agent override of dispatcher.config.runner_by_phase; NULL = use config default.';


COMMENT ON COLUMN dispatcher.agents.model_override IS 'Per-agent override of dispatcher.config.model_by_phase; NULL = use config default.';


COMMENT ON COLUMN dispatcher.agents.issue_title IS 'Issue title captured at claim time from the queue-snapshot enrichment. Lets the /admin/dispatcher recent-completions panel render a title without re-fetching from GitHub after the agent has completed and the issue may have left the active queue. Nullable — historical rows pre-dating issue #2820 have NULL and are not backfilled.';


COMMENT ON COLUMN dispatcher.agents.failure_summary IS 'One-line "what happened" string for failed / crashed / plan_blocked terminals. Populated by _mark_agent_terminal at terminal-time from failures.category + phase + exit_code + stderr tail (<=240 chars), then optionally upgraded by /diagnose-failure to the first 1-3 sentences of recommendation.reasoning. NULL for succeeded / needs_review rows and historical pre-#2900 rows. Rendered as a tooltip on the outcome glyph in the /admin/dispatcher Recently completed panel. Issue #2900.';


COMMENT ON COLUMN dispatcher.agents.priority IS 'Priority label captured at claim time (p0|p1|p2|p3|NULL). Written by both DispatcherDaemon._atomic_claim and scripts/dispatcher/task_claim.py. Reflects "priority when spawned"; does not retroactively update when the issue is relabeled on GitHub. Issue #2899.';


COMMENT ON COLUMN dispatcher.agents.merged_at IS 'Timestamp the PR squash-merge was observed by the daemon (``_merge_pr_and_advance``). One-way latch: written once, never cleared. Paired with the ``status=''succeeded''`` write at the same merge point. NULL for rows that never merged (push_and_pr failed, CI red after retries, etc.) and for pre-migration-35 rows without a recoverable merge signal. Issue #2953.';


COMMENT ON COLUMN dispatcher.agents.verified_at IS 'Timestamp the verify phase completed with verdict=VERIFIED. NULL when verify was intentionally skipped (see ``verify_skip_reason``), when verify crashed mid-phase, or for pre-migration-35 rows. A merged row with NULL ``verified_at`` AND NULL ``verify_skip_reason`` renders as amber ✓ in the admin cockpit — "shipped but post-merge bookkeeping incomplete". Issue #2953.';


COMMENT ON COLUMN dispatcher.agents.verify_skip_reason IS 'Non-null when verify is intentionally skipped — the row is "shipped + verify-does-not-apply" rather than "shipped + verify failed to run". Today the only written value is ''self_deploy'' (dispatcher-self-PR touches ``scripts/dispatcher/`` and the new daemon deploy will land mid-verify, making verify against the soon-to-be-replaced process useless). Planned future values: ''docs_only'' (``docs/`` / ``*.md`` only), ''ci_cd_only'' (``.github/workflows/`` only). No CHECK constraint — the set is daemon-code owned. Issue #2953.';


COMMENT ON COLUMN dispatcher.agents.retroed_at IS 'Timestamp the retro phase reached PHASE_RETRO_DONE. NULL when retro crashed, when the worktree was already gone at retro time (fast-path to cleanup_done), or for pre-migration-35 rows. A merged row with ``verified_at`` set but ``retroed_at`` NULL renders as amber ✓ — "shipped + verified but retro bookkeeping did not complete". Issue #2953.';


COMMENT ON COLUMN dispatcher.agents.agent_task_arn IS 'ECS task ARN of the per-agent agent-runner task (#3091). NULL for legacy subprocess-mode agents and between claim + ecs:RunTask in ecs-mode agents. Partial-indexed so the daemon reap pass scans only live ECS agents.';


COMMENT ON COLUMN dispatcher.agents.execution_mode IS 'One of ''subprocess'' (legacy fallback) | ''ecs'' (default since #3093) (per-agent Fargate task via ecs:RunTask). Set once at claim time from dispatcher.config.agent_execution_mode and held immutable across the agent''s lifetime. See #3091 / #3086 / #3078.';


COMMENT ON COLUMN dispatcher.agents.ralph_iterations_observed IS 'Count of ralph iterations observed by the ECS agent-runner HEAD-watcher (#3144). Atomically UPDATEd per iteration when the watcher persists a new dispatcher.ralph_patches row. Subprocess-mode agents keep this at 0 — the daemon-side watcher (#3042) persists ralph_patches but does not update this column. Issue #3144.';


COMMENT ON COLUMN dispatcher.agents.merge_unstick_attempts IS 'Count of stale-rollup merge-phase auto-unstick attempts for this agent (#2641). Bounded at 1 per agent lifetime: the first stale-rollup rejection (GitHub stderr "base branch policy prohibits the merge" while ci-passed on HEAD is SUCCESS) bumps this to 1 and the daemon pushes an empty commit to force a fresh rollup evaluation; a second rejection in the same agent''s lifetime routes through _handle_agent_failure with category merge_unstick_exhausted.';


COMMENT ON COLUMN dispatcher.agents.merge_conflict_attempts IS 'Count of fix_conflict-phase claude-resolution attempts for this agent (#3225). Bounded at FIX_CONFLICT_MAX_ATTEMPTS (default 2) per agent lifetime: each invocation of handle_fix_conflict increments this column before spawning the claude skill; when the value is already >= budget the handler advances to the conflict_unresolvable terminal without spending compute. Covers both the pre-push rebase-conflict path (push_and_pr) and the start-of-ralph baseline rebase-conflict path (secondary mitigation). See .claude/skills/task-v2-fix-conflict/SKILL.md.';


CREATE TABLE dispatcher.blocked_snapshots (
    snapshot_id uuid DEFAULT gen_random_uuid() NOT NULL,
    observed_at timestamp with time zone DEFAULT now() NOT NULL,
    blocked_depth integer NOT NULL,
    issue_numbers integer[] NOT NULL,
    issues_json jsonb DEFAULT '[]'::jsonb NOT NULL,
    run_id uuid
);


COMMENT ON TABLE dispatcher.blocked_snapshots IS 'Append-only history of observed ``status/blocked`` issues, one row per daemon snapshot tick. Written less frequently than queue_snapshots (blocked list changes slowly). Source of truth for the /admin/dispatcher blocked panel (issue #2820).';


COMMENT ON COLUMN dispatcher.blocked_snapshots.issue_numbers IS 'Issue numbers observed with label ``status/blocked`` and state=open.';


COMMENT ON COLUMN dispatcher.blocked_snapshots.issues_json IS 'Enriched issue metadata: [{number, title, labels, createdAt, body}, ...]. ``body`` is included so the API can parse ``Blocked by #N`` lines without another GitHub call.';


COMMENT ON COLUMN dispatcher.blocked_snapshots.run_id IS 'Owning daemon run. Cascade-deletes with the run row (same as queue_snapshots).';


CREATE TABLE dispatcher.commands (
    command_id bigint NOT NULL,
    command text NOT NULL,
    issued_by text NOT NULL,
    issued_at timestamp with time zone DEFAULT now() NOT NULL,
    consumed_at timestamp with time zone,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL
);


CREATE SEQUENCE dispatcher.commands_command_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE dispatcher.commands_command_id_seq OWNED BY dispatcher.commands.command_id;


CREATE TABLE dispatcher.config (
    key text NOT NULL,
    value jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_by text NOT NULL
);


CREATE TABLE dispatcher.diagnoses (
    diagnosis_id bigint NOT NULL,
    failure_id bigint NOT NULL,
    agent_id uuid NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    context jsonb NOT NULL,
    recommendation jsonb,
    outcome jsonb,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone
);


CREATE SEQUENCE dispatcher.diagnoses_diagnosis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE dispatcher.diagnoses_diagnosis_id_seq OWNED BY dispatcher.diagnoses.diagnosis_id;


CREATE TABLE dispatcher.failures (
    failure_id bigint NOT NULL,
    agent_id uuid,
    category text NOT NULL,
    detected_by text NOT NULL,
    details jsonb DEFAULT '{}'::jsonb NOT NULL,
    ts timestamp with time zone DEFAULT now() NOT NULL
);


COMMENT ON COLUMN dispatcher.failures.detected_by IS 'hook | scheduler | diagnoser — who wrote this row.';


CREATE SEQUENCE dispatcher.failures_failure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE dispatcher.failures_failure_id_seq OWNED BY dispatcher.failures.failure_id;


CREATE TABLE dispatcher.notifications (
    notification_id bigint NOT NULL,
    kind text NOT NULL,
    severity text NOT NULL,
    issue_number integer,
    pr_number integer,
    body text NOT NULL,
    issue_url text,
    sent_at timestamp with time zone,
    send_error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


CREATE SEQUENCE dispatcher.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE dispatcher.notifications_notification_id_seq OWNED BY dispatcher.notifications.notification_id;


CREATE TABLE dispatcher.phase_outputs (
    output_id bigint NOT NULL,
    agent_id uuid NOT NULL,
    phase text NOT NULL,
    output_json jsonb NOT NULL,
    ts timestamp with time zone DEFAULT now() NOT NULL,
    log_text text,
    attempt integer DEFAULT 0 NOT NULL,
    tokens_input bigint,
    tokens_output bigint,
    tokens_cache_read bigint,
    tokens_cache_write bigint,
    cost_usd numeric(10,4),
    model_used text,
    patch_id uuid
);


COMMENT ON COLUMN dispatcher.phase_outputs.log_text IS 'Full ephemeral phase log (stdout+stderr) captured from {worktree}/tmp/claude-p-<phase>.log at phase-finish time. Nullable for historical rows and for phases that failed before producing a log. Housekeeping tick prunes at 30 days along with output_json. See #2821.';


COMMENT ON COLUMN dispatcher.phase_outputs.attempt IS 'Retry attempt counter — matches dispatcher.agents.retries_used at the moment this phase ran. 0 = initial run. Each retry reset (_process_retry_markers) bumps the effective attempt for the next phase run. Issue #2872.';


COMMENT ON COLUMN dispatcher.phase_outputs.tokens_input IS 'Input tokens consumed by the phase (sum across all claude API turns). Parsed from the ``usage.input_tokens`` field of the ``claude -p --output-format json`` envelope. Nullable — historical rows and pre-JSON-envelope failures have no signal. Issue #2869.';


COMMENT ON COLUMN dispatcher.phase_outputs.tokens_output IS 'Output tokens emitted by the phase. Parsed from ``usage.output_tokens``. Nullable. Issue #2869.';


COMMENT ON COLUMN dispatcher.phase_outputs.tokens_cache_read IS 'Cache-read tokens (cheap tokens served from prompt-cache). Parsed from ``usage.cache_read_input_tokens``. Nullable. Issue #2869.';


COMMENT ON COLUMN dispatcher.phase_outputs.tokens_cache_write IS 'Cache-creation tokens (prompt written to cache for reuse). Parsed from ``usage.cache_creation_input_tokens``. Nullable. Issue #2869.';


COMMENT ON COLUMN dispatcher.phase_outputs.cost_usd IS 'Claude Code''s list-price cost estimate for the phase. Parsed from ``total_cost_usd``. NOT Max-plan-adjusted — comparable run-to-run but not actual billed spend. Nullable. Issue #2869.';


COMMENT ON COLUMN dispatcher.phase_outputs.model_used IS 'The resolved Claude model the phase ran on (e.g. ``"sonnet"``, ``"claude-sonnet-4-5"``). Free-form text — adding a new model never requires a migration. Nullable. Issue #2869.';


COMMENT ON COLUMN dispatcher.phase_outputs.patch_id IS 'FK to dispatcher.ralph_patches when this is the ralph SHIP row; NULL for every other phase and for ralph non-SHIP exits. ON DELETE SET NULL so phase_outputs survives patch cleanup. Issue #3012.';


CREATE SEQUENCE dispatcher.phase_outputs_output_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE dispatcher.phase_outputs_output_id_seq OWNED BY dispatcher.phase_outputs.output_id;


CREATE TABLE dispatcher.phase_transitions (
    transition_id bigint NOT NULL,
    agent_id uuid NOT NULL,
    phase text NOT NULL,
    ts timestamp with time zone DEFAULT now() NOT NULL,
    autocompact_count integer DEFAULT 0 NOT NULL
);


COMMENT ON TABLE dispatcher.phase_transitions IS 'Append-only phase log; replaces tmp/agent-status/*.txt. Phase is free-form text; validation is daemon-side.';


CREATE SEQUENCE dispatcher.phase_transitions_transition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE dispatcher.phase_transitions_transition_id_seq OWNED BY dispatcher.phase_transitions.transition_id;


CREATE TABLE dispatcher.queue_snapshots (
    snapshot_id uuid DEFAULT gen_random_uuid() NOT NULL,
    observed_at timestamp with time zone DEFAULT now() NOT NULL,
    queue_depth integer NOT NULL,
    issue_numbers integer[] NOT NULL,
    run_id uuid,
    issues_json jsonb DEFAULT '[]'::jsonb NOT NULL
);


COMMENT ON TABLE dispatcher.queue_snapshots IS 'Append-only history of observed agent/ready queue depths. Written by the daemon on each 30s scheduler tick (Phase 2+).';


COMMENT ON COLUMN dispatcher.queue_snapshots.issue_numbers IS 'Array of the observed issue numbers, ordered by priority as seen by the daemon at scan time.';


COMMENT ON COLUMN dispatcher.queue_snapshots.run_id IS 'Owning daemon run. Snapshots cascade-delete with the run row so forensic queries after a crash stay clean.';


COMMENT ON COLUMN dispatcher.queue_snapshots.issues_json IS 'Enriched issue metadata as observed at scan time: [{number, title, labels: [string], createdAt}, ...]. Populated by the daemon from the ``gh issue list --json number,title,labels,createdAt`` response. Source of truth for the /admin/dispatcher queue-ready panel (issue #2820). Kept in lock-step with ``issue_numbers`` — the two columns MUST describe the same issues in the same order.';


CREATE TABLE dispatcher.ralph_patches (
    patch_id uuid DEFAULT gen_random_uuid() NOT NULL,
    agent_id uuid NOT NULL,
    issue_number integer NOT NULL,
    patch_content text NOT NULL,
    commit_sha text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    iteration_n integer,
    verdict text
);


COMMENT ON TABLE dispatcher.ralph_patches IS 'Patches from ralph SHIP exits, persisted for the narrow window between SHIP and a successful gh pr create. Issue #3012.';


COMMENT ON COLUMN dispatcher.ralph_patches.patch_content IS 'git format-patch -1 HEAD --stdout output. Applied with git am when a retry inherits the prior SHIP.';


COMMENT ON COLUMN dispatcher.ralph_patches.commit_sha IS 'ralph''s HEAD SHA at SHIP time. Nullable — written when git rev-parse succeeds; informational only (the patch is the authoritative artifact).';


COMMENT ON COLUMN dispatcher.ralph_patches.iteration_n IS '1-based ralph iteration number at the time the row was written. NULL for legacy #3013 rows (pre-#3026 migration) and for SHIP rows (the SHIP DELETE-supersede path carries verdict=SHIP with iteration_n=NULL). Non-NULL for per-iteration intermediate rows. Issue #3026.';


COMMENT ON COLUMN dispatcher.ralph_patches.verdict IS 'Ralph verdict when the row was captured: LOOP (iteration continuing), SHIP (terminal SHIP), ABORT (gave up), or NULL (legacy pre-#3026). Not CHECK-constrained so forward-version daemons can introduce new verdicts without a migration. Issue #3026.';


CREATE TABLE dispatcher.retry_markers (
    marker_id bigint NOT NULL,
    agent_id uuid NOT NULL,
    reason text NOT NULL,
    attempt integer NOT NULL,
    retry_after_ts timestamp with time zone NOT NULL,
    resolved_at timestamp with time zone,
    CONSTRAINT retry_markers_attempt_check CHECK (((attempt >= 1) AND (attempt <= 3)))
);


CREATE SEQUENCE dispatcher.retry_markers_marker_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE dispatcher.retry_markers_marker_id_seq OWNED BY dispatcher.retry_markers.marker_id;


CREATE TABLE dispatcher.runs (
    run_id uuid DEFAULT gen_random_uuid() NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    stopped_at timestamp with time zone,
    heartbeat_ts timestamp with time zone DEFAULT now() NOT NULL,
    version_sha text NOT NULL,
    host text NOT NULL,
    pid integer NOT NULL
);


COMMENT ON TABLE dispatcher.runs IS 'One row per daemon boot. Latest row is the active lease.';


COMMENT ON COLUMN dispatcher.runs.heartbeat_ts IS 'Daemon updates every tick. CloudWatch alarm pages if stale > 5min.';


COMMENT ON COLUMN dispatcher.runs.version_sha IS 'Git SHA of the daemon build; supports forensic questions after a crash.';


CREATE TABLE dispatcher.terminal_outcomes (
    outcome_id bigint NOT NULL,
    agent_id uuid,
    issue_number integer,
    status text NOT NULL,
    ended_at timestamp with time zone DEFAULT now() NOT NULL
);


COMMENT ON TABLE dispatcher.terminal_outcomes IS 'Append-only ring buffer of terminal agent outcomes. Scanned by ``_evaluate_circuit_breaker`` over a rolling window to decide whether to auto-pause ``concurrency_cap``. Issue #2860.';


COMMENT ON COLUMN dispatcher.terminal_outcomes.agent_id IS 'Nullable — synthetic test inputs may have no agent row. Production writes always carry this.';


COMMENT ON COLUMN dispatcher.terminal_outcomes.status IS 'Free-form text (succeeded | failed | crashed | plan_blocked | needs_review | ...). Classifier in daemon decides which count as bad.';


CREATE SEQUENCE dispatcher.terminal_outcomes_outcome_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE dispatcher.terminal_outcomes_outcome_id_seq OWNED BY dispatcher.terminal_outcomes.outcome_id;


CREATE TABLE dispatcher.unrecognized_diagnoser_actions (
    id bigint NOT NULL,
    diagnosis_id bigint NOT NULL,
    action_name text NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    observed_at timestamp with time zone DEFAULT now() NOT NULL
);


COMMENT ON TABLE dispatcher.unrecognized_diagnoser_actions IS 'Diagnoser actions the daemon did not recognize. Operator reviews periodically; 5+ instances of a new action is signal to implement a handler. See issue #3032.';


COMMENT ON COLUMN dispatcher.unrecognized_diagnoser_actions.action_name IS 'The action string as emitted by the diagnoser (e.g. "split_task"). Not constrained — anything the LLM proposed that was not in the known set lands here.';


COMMENT ON COLUMN dispatcher.unrecognized_diagnoser_actions.payload IS 'The full recommendation dict (action + reasoning + any payload fields the LLM proposed) serialized as JSONB. Lets a future handler implementer see the proposed shape without replaying the diagnosis.';


CREATE SEQUENCE dispatcher.unrecognized_diagnoser_actions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE dispatcher.unrecognized_diagnoser_actions_id_seq OWNED BY dispatcher.unrecognized_diagnoser_actions.id;


CREATE TABLE public.alert_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    subscription_id uuid NOT NULL,
    document_id uuid,
    ruling_id uuid,
    triggered_at timestamp with time zone DEFAULT now() NOT NULL,
    included_in_digest_at timestamp with time zone,
    digest_sent boolean DEFAULT false NOT NULL
);


CREATE TABLE public.alert_subscriptions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    alert_type public.alert_type NOT NULL,
    filters jsonb DEFAULT '{}'::jsonb NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


CREATE TABLE public.refresh_tokens (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    token_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


CREATE TABLE public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email text NOT NULL,
    email_verified boolean DEFAULT false NOT NULL,
    password_hash text,
    display_name text,
    role text DEFAULT 'user'::text NOT NULL,
    api_key text,
    ai_budget_daily integer DEFAULT 20 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    last_login_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    google_id text
);


CREATE TABLE staging.captures (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    court_id uuid NOT NULL,
    scraper_id text NOT NULL,
    source_url text NOT NULL,
    raw_content text NOT NULL,
    raw_content_type text NOT NULL,
    content_hash text NOT NULL,
    capture_metadata jsonb,
    captured_at timestamp with time zone NOT NULL,
    validation_status public.validation_status DEFAULT 'pending'::public.validation_status NOT NULL,
    validation_notes text,
    validated_at timestamp with time zone,
    validated_by text,
    promoted_at timestamp with time zone,
    promoted_document_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


CREATE TABLE staging.ruled_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    capture_id uuid NOT NULL,
    court_id uuid NOT NULL,
    case_number_raw text,
    judge_name_raw text,
    department_raw text,
    hearing_date date,
    ruling_text text,
    motion_type_raw text,
    outcome_raw text,
    parsed_metadata jsonb,
    validation_status public.validation_status DEFAULT 'pending'::public.validation_status NOT NULL,
    validation_notes text,
    validated_at timestamp with time zone,
    promoted_at timestamp with time zone,
    promoted_ruling_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


CREATE TABLE telemetry.data_quality_metrics (
    id bigint NOT NULL,
    recorded_at timestamp with time zone DEFAULT now() NOT NULL,
    county text NOT NULL,
    metric_name text NOT NULL,
    metric_value numeric NOT NULL,
    metadata jsonb
);


CREATE SEQUENCE telemetry.data_quality_metrics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE telemetry.data_quality_metrics_id_seq OWNED BY telemetry.data_quality_metrics.id;


CREATE TABLE telemetry.scraper_runs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    scraper_id text NOT NULL,
    court_id uuid,
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    status text NOT NULL,
    records_captured integer DEFAULT 0 NOT NULL,
    records_failed integer DEFAULT 0 NOT NULL,
    error_message text,
    error_details jsonb,
    response_time_ms integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


CREATE TABLE telemetry.validation_results (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    document_id uuid NOT NULL,
    ruling_id uuid,
    result text NOT NULL,
    reason text,
    model text,
    input_tokens integer,
    output_tokens integer,
    latency_ms integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT validation_results_result_check CHECK ((result = ANY (ARRAY['pass'::text, 'flag'::text, 'fail'::text, 'error'::text])))
);


COMMENT ON TABLE telemetry.validation_results IS 'LLM validation outcomes for ingested documents. One row per validation check.';


COMMENT ON COLUMN telemetry.validation_results.result IS 'Validation outcome: pass (write normally), flag (write + review), fail (skip write), error (LLM call failed).';


COMMENT ON COLUMN telemetry.validation_results.reason IS 'Human-readable reason for flag/fail results. NULL for pass results.';


COMMENT ON COLUMN telemetry.validation_results.model IS 'LLM model used for validation (e.g. claude-haiku-4-5-20251001).';


COMMENT ON COLUMN telemetry.validation_results.latency_ms IS 'Wall-clock time for the validation LLM call in milliseconds.';


ALTER TABLE ONLY derived.court_directory_snapshots ALTER COLUMN id SET DEFAULT nextval('derived.court_directory_snapshots_id_seq'::regclass);


ALTER TABLE ONLY dispatcher.commands ALTER COLUMN command_id SET DEFAULT nextval('dispatcher.commands_command_id_seq'::regclass);


ALTER TABLE ONLY dispatcher.diagnoses ALTER COLUMN diagnosis_id SET DEFAULT nextval('dispatcher.diagnoses_diagnosis_id_seq'::regclass);


ALTER TABLE ONLY dispatcher.failures ALTER COLUMN failure_id SET DEFAULT nextval('dispatcher.failures_failure_id_seq'::regclass);


ALTER TABLE ONLY dispatcher.notifications ALTER COLUMN notification_id SET DEFAULT nextval('dispatcher.notifications_notification_id_seq'::regclass);


ALTER TABLE ONLY dispatcher.phase_outputs ALTER COLUMN output_id SET DEFAULT nextval('dispatcher.phase_outputs_output_id_seq'::regclass);


ALTER TABLE ONLY dispatcher.phase_transitions ALTER COLUMN transition_id SET DEFAULT nextval('dispatcher.phase_transitions_transition_id_seq'::regclass);


ALTER TABLE ONLY dispatcher.retry_markers ALTER COLUMN marker_id SET DEFAULT nextval('dispatcher.retry_markers_marker_id_seq'::regclass);


ALTER TABLE ONLY dispatcher.terminal_outcomes ALTER COLUMN outcome_id SET DEFAULT nextval('dispatcher.terminal_outcomes_outcome_id_seq'::regclass);


ALTER TABLE ONLY dispatcher.unrecognized_diagnoser_actions ALTER COLUMN id SET DEFAULT nextval('dispatcher.unrecognized_diagnoser_actions_id_seq'::regclass);


ALTER TABLE ONLY telemetry.data_quality_metrics ALTER COLUMN id SET DEFAULT nextval('telemetry.data_quality_metrics_id_seq'::regclass);


ALTER TABLE ONLY derived.attorney_aliases
    ADD CONSTRAINT attorney_aliases_pkey PRIMARY KEY (id);


ALTER TABLE ONLY derived.attorneys
    ADD CONSTRAINT attorneys_pkey PRIMARY KEY (id);


ALTER TABLE ONLY derived.case_attorneys
    ADD CONSTRAINT case_attorneys_pkey PRIMARY KEY (id);


ALTER TABLE ONLY derived.case_judges
    ADD CONSTRAINT case_judges_pkey PRIMARY KEY (case_id, judge_id);


ALTER TABLE ONLY derived.case_parties
    ADD CONSTRAINT case_parties_pkey PRIMARY KEY (id);


ALTER TABLE ONLY derived.cases
    ADD CONSTRAINT cases_court_id_case_number_key UNIQUE (court_id, case_number);


ALTER TABLE ONLY derived.cases
    ADD CONSTRAINT cases_pkey PRIMARY KEY (id);


ALTER TABLE ONLY derived.court_directory_snapshots
    ADD CONSTRAINT court_directory_snapshots_pkey PRIMARY KEY (id);


ALTER TABLE ONLY derived.courts
    ADD CONSTRAINT courts_court_code_key UNIQUE (court_code);


ALTER TABLE ONLY derived.courts
    ADD CONSTRAINT courts_pkey PRIMARY KEY (id);


ALTER TABLE ONLY derived.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


ALTER TABLE ONLY derived.judge_aliases
    ADD CONSTRAINT judge_aliases_pkey PRIMARY KEY (id);


ALTER TABLE ONLY derived.judges
    ADD CONSTRAINT judges_canonical_name_court_id_key UNIQUE (canonical_name, court_id);


ALTER TABLE ONLY derived.judges
    ADD CONSTRAINT judges_pkey PRIMARY KEY (id);


ALTER TABLE ONLY derived.parties
    ADD CONSTRAINT parties_pkey PRIMARY KEY (id);


ALTER TABLE ONLY derived.party_aliases
    ADD CONSTRAINT party_aliases_pkey PRIMARY KEY (id);


ALTER TABLE ONLY derived.rulings
    ADD CONSTRAINT rulings_pkey PRIMARY KEY (id);


ALTER TABLE ONLY derived.case_attorneys
    ADD CONSTRAINT uq_case_attorneys_case_attorney_role UNIQUE (case_id, attorney_id, role);


ALTER TABLE ONLY derived.case_parties
    ADD CONSTRAINT uq_case_parties_case_party_role UNIQUE (case_id, party_id, role);


ALTER TABLE ONLY derived.rulings
    ADD CONSTRAINT uq_rulings_document_id UNIQUE (document_id);


ALTER TABLE ONLY dispatcher.agents
    ADD CONSTRAINT agents_pkey PRIMARY KEY (agent_id);


ALTER TABLE ONLY dispatcher.blocked_snapshots
    ADD CONSTRAINT blocked_snapshots_pkey PRIMARY KEY (snapshot_id);


ALTER TABLE ONLY dispatcher.commands
    ADD CONSTRAINT commands_pkey PRIMARY KEY (command_id);


ALTER TABLE ONLY dispatcher.config
    ADD CONSTRAINT config_pkey PRIMARY KEY (key);


ALTER TABLE ONLY dispatcher.diagnoses
    ADD CONSTRAINT diagnoses_pkey PRIMARY KEY (diagnosis_id);


ALTER TABLE ONLY dispatcher.failures
    ADD CONSTRAINT failures_pkey PRIMARY KEY (failure_id);


ALTER TABLE ONLY dispatcher.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (notification_id);


ALTER TABLE ONLY dispatcher.phase_outputs
    ADD CONSTRAINT phase_outputs_pkey PRIMARY KEY (output_id);


ALTER TABLE ONLY dispatcher.phase_transitions
    ADD CONSTRAINT phase_transitions_pkey PRIMARY KEY (transition_id);


ALTER TABLE ONLY dispatcher.queue_snapshots
    ADD CONSTRAINT queue_snapshots_pkey PRIMARY KEY (snapshot_id);


ALTER TABLE ONLY dispatcher.ralph_patches
    ADD CONSTRAINT ralph_patches_pkey PRIMARY KEY (patch_id);


ALTER TABLE ONLY dispatcher.retry_markers
    ADD CONSTRAINT retry_markers_pkey PRIMARY KEY (marker_id);


ALTER TABLE ONLY dispatcher.runs
    ADD CONSTRAINT runs_pkey PRIMARY KEY (run_id);


ALTER TABLE ONLY dispatcher.terminal_outcomes
    ADD CONSTRAINT terminal_outcomes_pkey PRIMARY KEY (outcome_id);


ALTER TABLE ONLY dispatcher.unrecognized_diagnoser_actions
    ADD CONSTRAINT unrecognized_diagnoser_actions_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.alert_events
    ADD CONSTRAINT alert_events_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.alert_subscriptions
    ADD CONSTRAINT alert_subscriptions_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_hash_key UNIQUE (token_hash);


ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_api_key_key UNIQUE (api_key);


ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_google_id_key UNIQUE (google_id);


ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


ALTER TABLE ONLY staging.captures
    ADD CONSTRAINT captures_pkey PRIMARY KEY (id);


ALTER TABLE ONLY staging.ruled_items
    ADD CONSTRAINT ruled_items_pkey PRIMARY KEY (id);


ALTER TABLE ONLY telemetry.data_quality_metrics
    ADD CONSTRAINT data_quality_metrics_pkey PRIMARY KEY (id);


ALTER TABLE ONLY telemetry.scraper_runs
    ADD CONSTRAINT scraper_runs_pkey PRIMARY KEY (id);


ALTER TABLE ONLY telemetry.validation_results
    ADD CONSTRAINT validation_results_pkey PRIMARY KEY (id);


CREATE INDEX idx_attorney_aliases_raw_name ON derived.attorney_aliases USING btree (lower(raw_name));


CREATE INDEX idx_attorneys_bar ON derived.attorneys USING btree (bar_state, bar_number) WHERE (bar_number IS NOT NULL);


CREATE INDEX idx_case_attorneys_attorney_id ON derived.case_attorneys USING btree (attorney_id);


CREATE INDEX idx_case_judges_judge_id ON derived.case_judges USING btree (judge_id);


CREATE INDEX idx_case_parties_party_id ON derived.case_parties USING btree (party_id);


CREATE INDEX idx_cases_case_number ON derived.cases USING btree (case_number);


CREATE INDEX idx_cases_case_type ON derived.cases USING btree (case_type);


CREATE INDEX idx_cases_court_id ON derived.cases USING btree (court_id);


CREATE INDEX idx_cases_filed_at ON derived.cases USING btree (filed_at DESC);


CREATE INDEX idx_cases_keyset_created ON derived.cases USING btree (created_at DESC, id DESC);


CREATE INDEX idx_cases_number_norm ON derived.cases USING btree (case_number_normalized);


CREATE INDEX idx_cases_status ON derived.cases USING btree (case_status) WHERE (case_status = 'active'::text);


CREATE INDEX idx_court_dir_lookup ON derived.court_directory_snapshots USING btree (court_id, captured_at DESC);


CREATE INDEX idx_courts_county ON derived.courts USING btree (county);


CREATE INDEX idx_courts_state ON derived.courts USING btree (state);


CREATE INDEX idx_documents_active ON derived.documents USING btree (status) WHERE (status = 'active'::public.document_status);


CREATE INDEX idx_documents_captured_at ON derived.documents USING btree (captured_at DESC);


CREATE INDEX idx_documents_case_id ON derived.documents USING btree (case_id);


CREATE INDEX idx_documents_court_id ON derived.documents USING btree (court_id);


CREATE INDEX idx_documents_hash ON derived.documents USING btree (content_hash);


CREATE INDEX idx_documents_hearing_date ON derived.documents USING btree (hearing_date);


CREATE INDEX idx_judge_aliases_raw_name ON derived.judge_aliases USING btree (lower(raw_name));


CREATE INDEX idx_parties_canonical_name_lower ON derived.parties USING btree (lower(canonical_name));


CREATE INDEX idx_party_aliases_raw_name ON derived.party_aliases USING btree (lower(raw_name));


CREATE INDEX idx_rulings_case_id ON derived.rulings USING btree (case_id);


CREATE INDEX idx_rulings_court_id ON derived.rulings USING btree (court_id);


CREATE INDEX idx_rulings_hearing_date ON derived.rulings USING btree (hearing_date DESC);


CREATE INDEX idx_rulings_judge_id ON derived.rulings USING btree (judge_id);


CREATE INDEX idx_rulings_judge_motion ON derived.rulings USING btree (judge_id, motion_type, outcome);


CREATE INDEX idx_rulings_judge_outcome ON derived.rulings USING btree (judge_id, outcome, hearing_date DESC);


CREATE INDEX idx_rulings_keyset_hearing ON derived.rulings USING btree (hearing_date DESC, id DESC);


CREATE INDEX idx_rulings_motion_type ON derived.rulings USING btree (motion_type);


CREATE INDEX idx_rulings_outcome ON derived.rulings USING btree (outcome);


CREATE INDEX idx_rulings_posted_at ON derived.rulings USING btree (posted_at DESC);


CREATE UNIQUE INDEX uq_rulings_case_text_hash ON derived.rulings USING btree (case_id, ruling_text_hash) WHERE (ruling_text_hash IS NOT NULL);


CREATE INDEX dispatcher_agents_task_arn_idx ON dispatcher.agents USING btree (agent_task_arn) WHERE (agent_task_arn IS NOT NULL);


CREATE UNIQUE INDEX idx_dispatcher_agents_active_issue ON dispatcher.agents USING btree (issue_number) WHERE (status = ANY (ARRAY['running'::text, 'retrying'::text]));


COMMENT ON INDEX dispatcher.idx_dispatcher_agents_active_issue IS 'Atomic-claim uniqueness: at most one active (running/retrying) agent per issue. INSERT conflicts on this index mean another daemon claimed first.';


CREATE INDEX idx_dispatcher_agents_issue_number ON dispatcher.agents USING btree (issue_number);


CREATE INDEX idx_dispatcher_agents_running ON dispatcher.agents USING btree (status) WHERE (status = 'running'::text);


CREATE INDEX idx_dispatcher_blocked_snapshots_observed_at ON dispatcher.blocked_snapshots USING btree (observed_at DESC);


CREATE INDEX idx_dispatcher_commands_unconsumed ON dispatcher.commands USING btree (consumed_at) WHERE (consumed_at IS NULL);


CREATE INDEX idx_dispatcher_diagnoses_agent_id ON dispatcher.diagnoses USING btree (agent_id);


CREATE INDEX idx_dispatcher_diagnoses_pending ON dispatcher.diagnoses USING btree (status) WHERE (status = 'pending'::text);


CREATE INDEX idx_dispatcher_failures_category_ts ON dispatcher.failures USING btree (category, ts DESC);


CREATE INDEX idx_dispatcher_failures_ts ON dispatcher.failures USING btree (ts DESC);


CREATE INDEX idx_dispatcher_notifications_created_at ON dispatcher.notifications USING btree (created_at DESC);


CREATE INDEX idx_dispatcher_notifications_human_attention_unsent ON dispatcher.notifications USING btree (severity, sent_at) WHERE (severity = 'human_attention'::text);


CREATE UNIQUE INDEX idx_dispatcher_phase_outputs_agent_phase_attempt ON dispatcher.phase_outputs USING btree (agent_id, phase, attempt);


CREATE INDEX idx_dispatcher_phase_transitions_agent_ts ON dispatcher.phase_transitions USING btree (agent_id, ts DESC);


CREATE INDEX idx_dispatcher_queue_snapshots_observed_at ON dispatcher.queue_snapshots USING btree (observed_at DESC);


CREATE INDEX idx_dispatcher_retry_markers_pending ON dispatcher.retry_markers USING btree (retry_after_ts) WHERE (resolved_at IS NULL);


CREATE INDEX idx_dispatcher_terminal_outcomes_ended_at ON dispatcher.terminal_outcomes USING btree (ended_at DESC);


CREATE INDEX idx_dispatcher_unrec_actions_action ON dispatcher.unrecognized_diagnoser_actions USING btree (action_name, observed_at DESC);


CREATE INDEX ralph_patches_created_at_idx ON dispatcher.ralph_patches USING btree (created_at);


CREATE INDEX ralph_patches_issue_idx ON dispatcher.ralph_patches USING btree (issue_number);


CREATE INDEX idx_alert_events_sub_id ON public.alert_events USING btree (subscription_id);


CREATE INDEX idx_alert_events_unsent ON public.alert_events USING btree (digest_sent, triggered_at) WHERE (NOT digest_sent);


CREATE INDEX idx_refresh_tokens_expires ON public.refresh_tokens USING btree (expires_at);


CREATE INDEX idx_refresh_tokens_user_id ON public.refresh_tokens USING btree (user_id);


CREATE INDEX idx_staging_captures_at ON staging.captures USING btree (captured_at DESC);


CREATE INDEX idx_staging_captures_court_id ON staging.captures USING btree (court_id);


CREATE INDEX idx_staging_captures_status ON staging.captures USING btree (validation_status);


CREATE INDEX idx_staging_ruled_status ON staging.ruled_items USING btree (validation_status);


CREATE INDEX idx_dqm_county_metric_time ON telemetry.data_quality_metrics USING btree (county, metric_name, recorded_at DESC);


CREATE INDEX idx_scraper_runs_scraper_id ON telemetry.scraper_runs USING btree (scraper_id, started_at DESC);


CREATE INDEX idx_validation_results_document_id ON telemetry.validation_results USING btree (document_id);


CREATE INDEX idx_validation_results_result ON telemetry.validation_results USING btree (result);


CREATE TRIGGER trg_attorneys_updated_at BEFORE UPDATE ON derived.attorneys FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


CREATE TRIGGER trg_cases_updated_at BEFORE UPDATE ON derived.cases FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


CREATE TRIGGER trg_courts_updated_at BEFORE UPDATE ON derived.courts FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


CREATE TRIGGER trg_judges_updated_at BEFORE UPDATE ON derived.judges FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


CREATE TRIGGER trg_parties_updated_at BEFORE UPDATE ON derived.parties FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


CREATE TRIGGER trg_rulings_updated_at BEFORE UPDATE ON derived.rulings FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


CREATE TRIGGER trg_alert_subscriptions_updated_at BEFORE UPDATE ON public.alert_subscriptions FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


ALTER TABLE ONLY derived.attorney_aliases
    ADD CONSTRAINT attorney_aliases_attorney_id_fkey FOREIGN KEY (attorney_id) REFERENCES derived.attorneys(id) ON DELETE CASCADE;


ALTER TABLE ONLY derived.case_attorneys
    ADD CONSTRAINT case_attorneys_attorney_id_fkey FOREIGN KEY (attorney_id) REFERENCES derived.attorneys(id);


ALTER TABLE ONLY derived.case_attorneys
    ADD CONSTRAINT case_attorneys_case_id_fkey FOREIGN KEY (case_id) REFERENCES derived.cases(id) ON DELETE CASCADE;


ALTER TABLE ONLY derived.case_attorneys
    ADD CONSTRAINT case_attorneys_party_id_fkey FOREIGN KEY (party_id) REFERENCES derived.parties(id);


ALTER TABLE ONLY derived.case_judges
    ADD CONSTRAINT case_judges_case_id_fkey FOREIGN KEY (case_id) REFERENCES derived.cases(id) ON DELETE CASCADE;


ALTER TABLE ONLY derived.case_judges
    ADD CONSTRAINT case_judges_judge_id_fkey FOREIGN KEY (judge_id) REFERENCES derived.judges(id);


ALTER TABLE ONLY derived.case_parties
    ADD CONSTRAINT case_parties_case_id_fkey FOREIGN KEY (case_id) REFERENCES derived.cases(id) ON DELETE CASCADE;


ALTER TABLE ONLY derived.case_parties
    ADD CONSTRAINT case_parties_party_id_fkey FOREIGN KEY (party_id) REFERENCES derived.parties(id);


ALTER TABLE ONLY derived.cases
    ADD CONSTRAINT cases_court_id_fkey FOREIGN KEY (court_id) REFERENCES derived.courts(id);


ALTER TABLE ONLY derived.documents
    ADD CONSTRAINT documents_case_id_fkey FOREIGN KEY (case_id) REFERENCES derived.cases(id);


ALTER TABLE ONLY derived.documents
    ADD CONSTRAINT documents_court_id_fkey FOREIGN KEY (court_id) REFERENCES derived.courts(id);


ALTER TABLE ONLY derived.documents
    ADD CONSTRAINT documents_previous_version_id_fkey FOREIGN KEY (previous_version_id) REFERENCES derived.documents(id);


ALTER TABLE ONLY derived.judge_aliases
    ADD CONSTRAINT judge_aliases_judge_id_fkey FOREIGN KEY (judge_id) REFERENCES derived.judges(id) ON DELETE CASCADE;


ALTER TABLE ONLY derived.judges
    ADD CONSTRAINT judges_court_id_fkey FOREIGN KEY (court_id) REFERENCES derived.courts(id);


ALTER TABLE ONLY derived.party_aliases
    ADD CONSTRAINT party_aliases_party_id_fkey FOREIGN KEY (party_id) REFERENCES derived.parties(id) ON DELETE CASCADE;


ALTER TABLE ONLY derived.rulings
    ADD CONSTRAINT rulings_case_id_fkey FOREIGN KEY (case_id) REFERENCES derived.cases(id);


ALTER TABLE ONLY derived.rulings
    ADD CONSTRAINT rulings_court_id_fkey FOREIGN KEY (court_id) REFERENCES derived.courts(id);


ALTER TABLE ONLY derived.rulings
    ADD CONSTRAINT rulings_document_id_fkey FOREIGN KEY (document_id) REFERENCES derived.documents(id);


ALTER TABLE ONLY derived.rulings
    ADD CONSTRAINT rulings_judge_id_fkey FOREIGN KEY (judge_id) REFERENCES derived.judges(id);


ALTER TABLE ONLY dispatcher.agents
    ADD CONSTRAINT agents_parent_run_id_fkey FOREIGN KEY (parent_run_id) REFERENCES dispatcher.runs(run_id);


ALTER TABLE ONLY dispatcher.blocked_snapshots
    ADD CONSTRAINT blocked_snapshots_run_id_fkey FOREIGN KEY (run_id) REFERENCES dispatcher.runs(run_id) ON DELETE CASCADE;


ALTER TABLE ONLY dispatcher.diagnoses
    ADD CONSTRAINT diagnoses_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES dispatcher.agents(agent_id);


ALTER TABLE ONLY dispatcher.diagnoses
    ADD CONSTRAINT diagnoses_failure_id_fkey FOREIGN KEY (failure_id) REFERENCES dispatcher.failures(failure_id);


ALTER TABLE ONLY dispatcher.failures
    ADD CONSTRAINT failures_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES dispatcher.agents(agent_id);


ALTER TABLE ONLY dispatcher.phase_outputs
    ADD CONSTRAINT phase_outputs_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES dispatcher.agents(agent_id);


ALTER TABLE ONLY dispatcher.phase_outputs
    ADD CONSTRAINT phase_outputs_patch_id_fkey FOREIGN KEY (patch_id) REFERENCES dispatcher.ralph_patches(patch_id) ON DELETE SET NULL;


ALTER TABLE ONLY dispatcher.phase_transitions
    ADD CONSTRAINT phase_transitions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES dispatcher.agents(agent_id);


ALTER TABLE ONLY dispatcher.queue_snapshots
    ADD CONSTRAINT queue_snapshots_run_id_fkey FOREIGN KEY (run_id) REFERENCES dispatcher.runs(run_id) ON DELETE CASCADE;


ALTER TABLE ONLY dispatcher.ralph_patches
    ADD CONSTRAINT ralph_patches_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES dispatcher.agents(agent_id);


ALTER TABLE ONLY dispatcher.retry_markers
    ADD CONSTRAINT retry_markers_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES dispatcher.agents(agent_id);


ALTER TABLE ONLY dispatcher.unrecognized_diagnoser_actions
    ADD CONSTRAINT unrecognized_diagnoser_actions_diagnosis_id_fkey FOREIGN KEY (diagnosis_id) REFERENCES dispatcher.diagnoses(diagnosis_id);


ALTER TABLE ONLY public.alert_events
    ADD CONSTRAINT alert_events_document_id_fkey FOREIGN KEY (document_id) REFERENCES derived.documents(id);


ALTER TABLE ONLY public.alert_events
    ADD CONSTRAINT alert_events_ruling_id_fkey FOREIGN KEY (ruling_id) REFERENCES derived.rulings(id);


ALTER TABLE ONLY public.alert_events
    ADD CONSTRAINT alert_events_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.alert_subscriptions(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.alert_subscriptions
    ADD CONSTRAINT alert_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


ALTER TABLE ONLY staging.ruled_items
    ADD CONSTRAINT ruled_items_capture_id_fkey FOREIGN KEY (capture_id) REFERENCES staging.captures(id);


ALTER TABLE ONLY telemetry.scraper_runs
    ADD CONSTRAINT scraper_runs_court_id_fkey FOREIGN KEY (court_id) REFERENCES derived.courts(id);



