"""Deterministic document ID generation for split rulings.

When a multi-case document (e.g. an OC calendar PDF containing 5 separate
rulings) is split into individual ruling records, each split ruling needs its
own unique ``document_id``.  This module provides a deterministic UUID5-based
generator so re-processing the same document always produces the same IDs.

This function is used by:
  - ``ingestion.worker._llm_split_document()``
  - ``scripts/reingest_from_s3.py``
"""

from __future__ import annotations

import uuid

# UUID namespace for generating deterministic split document IDs.
# Using NAMESPACE_URL is arbitrary but stable -- the important thing is
# consistency across re-processing runs.
_SPLIT_UUID_NAMESPACE = uuid.UUID("a3f1b2c4-d5e6-7890-abcd-ef1234567890")


def derive_parent_document_id(content_hash: str) -> str:
    """Derive the deterministic parent ``document_id`` from a content hash.

    Mirrors the logic in ``framework.base.BaseScraper._process_document``:
    ``uuid5(NAMESPACE_URL, content_hash)``.  Used by ``is_split_child_id``
    to distinguish split children from regular scraper-generated IDs.

    Args:
        content_hash: The SHA-256 hex digest of the raw document content.

    Returns:
        The UUID string that a non-split scraper would assign for this content.
    """
    return str(uuid.uuid5(uuid.NAMESPACE_URL, content_hash))


def is_split_child_id(document_id: str, content_hash: str | None = None) -> bool:
    """Check whether a document_id was generated by ``make_split_document_id()``.

    Both regular scraper document IDs and split child IDs are UUID v5 (since
    #302 made scraper IDs deterministic).  The version bits alone cannot
    distinguish the two.  Instead, we compare the given ``document_id``
    against the UUID that would be generated by the regular scraper path
    (``uuid5(NAMESPACE_URL, content_hash)``).  If they match, it's a regular
    parent document; if not, it must be a split child (or some unknown
    legacy UUID, which we conservatively treat as a regular document).

    A split child always has a parent document in the DB sharing the same
    ``content_hash`` but a different ``document_id`` (derived via
    ``make_split_document_id``).

    If ``content_hash`` is not provided, falls back to the legacy
    version-check (which will mis-classify v5 scraper IDs as split children,
    but preserves behaviour for callers that cannot supply a hash).

    Args:
        document_id: The document UUID string to check.
        content_hash: The SHA-256 hex digest of the document's raw content.
            When provided, enables accurate split-child detection.  When
            omitted, falls back to UUID-version check (legacy behaviour).

    Returns:
        ``True`` if the ID is a split child, ``False`` otherwise.
    """
    try:
        parsed = uuid.UUID(document_id)
    except (ValueError, AttributeError):
        return False
    if parsed.version != 5:
        # UUID v4 or other — definitely not a split child (those are always v5).
        return False
    if content_hash is None:
        # Legacy fallback: without content_hash we can't distinguish; assume
        # split child based on version.
        return True
    # Compare against the regular parent derivation.  If they match, this
    # is a parent document, not a split child.
    return document_id != derive_parent_document_id(content_hash)


def make_split_document_id(original_document_id: str, split_index: int) -> str:
    """Generate a deterministic synthetic document_id for a split ruling.

    Uses UUID5 with a fixed namespace to produce the same ID every time the
    same document is re-processed.  This ensures idempotent re-ingestion:
    the ``ON CONFLICT (document_id) DO UPDATE`` in ``insert_ruling()`` will
    upsert cleanly.

    Args:
        original_document_id: The original document UUID string from the scraper.
        split_index: Zero-based index of this ruling within the split results.

    Returns:
        A UUID string suitable for use as ``rulings.document_id``.
    """
    return str(uuid.uuid5(_SPLIT_UUID_NAMESPACE, f"{original_document_id}:{split_index}"))
