/**
 * Lightweight HTML sanitizer for ruling text HTML.
 *
 * Defence-in-depth: the HTML is generated by our own LLM formatting pipeline
 * (trusted source), but we sanitize before rendering to guard against any
 * injection that might slip through.
 *
 * Approach: allowlist of safe tags and attributes. Everything else is stripped.
 * This avoids adding a runtime dependency like DOMPurify while covering the
 * narrow set of tags the ruling formatter produces.
 */

/** Tags allowed in ruling HTML. Everything else is stripped (content preserved). */
const ALLOWED_TAGS = new Set([
  'div',
  'header',
  'section',
  'span',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'p',
  'ul',
  'ol',
  'li',
  'strong',
  'em',
  'b',
  'i',
  'br',
  'blockquote',
  'pre',
  'code',
  'table',
  'thead',
  'tbody',
  'tr',
  'th',
  'td',
  'a',
  'sup',
  'sub',
]);

/** Attributes allowed on any tag. Only `class` and `href` (for links) are permitted. */
const ALLOWED_ATTRS = new Set(['class', 'href']);

/** Regex to match an HTML tag (opening, closing, or self-closing). */
const TAG_RE = /<\/?([a-zA-Z][a-zA-Z0-9]*)\b([^>]*)?\/?>/g;

/** Regex to match a single attribute within a tag. */
const ATTR_RE = /([a-zA-Z][a-zA-Z0-9-]*)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g;

/**
 * Sanitize HTML by stripping disallowed tags and attributes.
 *
 * - Allowed tags are kept with only their allowed attributes.
 * - Disallowed tags are removed but their text content is preserved.
 * - Script and style tags (and their content) are removed entirely.
 *
 * @param html - Raw HTML string to sanitize.
 * @returns Sanitized HTML string safe for `dangerouslySetInnerHTML`.
 */
export function sanitizeRulingHtml(html: string): string {
  // Step 1: Remove <script> and <style> tags and their contents entirely.
  let result = html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, '');
  result = result.replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, '');

  // Step 2: Remove HTML comments.
  result = result.replace(/<!--[\s\S]*?-->/g, '');

  // Step 3: Process remaining tags — keep allowed ones, strip others (preserving content).
  result = result.replace(TAG_RE, (match, tagName: string, attrString: string | undefined) => {
    const tag = tagName.toLowerCase();
    const isClosing = match.startsWith('</');

    if (!ALLOWED_TAGS.has(tag)) {
      return ''; // Strip tag but keep surrounding text content
    }

    if (isClosing) {
      return `</${tag}>`;
    }

    // Rebuild allowed attributes only
    const attrs: string[] = [];
    if (attrString) {
      let attrMatch: RegExpExecArray | null;
      ATTR_RE.lastIndex = 0;
      while ((attrMatch = ATTR_RE.exec(attrString)) !== null) {
        const attrName = attrMatch[1].toLowerCase();
        const attrValue = attrMatch[2] ?? attrMatch[3] ?? attrMatch[4] ?? '';

        if (!ALLOWED_ATTRS.has(attrName)) {
          continue;
        }

        // For href, only allow safe protocols
        if (attrName === 'href') {
          const trimmed = attrValue.trim().toLowerCase();
          if (
            !trimmed.startsWith('http://') &&
            !trimmed.startsWith('https://') &&
            !trimmed.startsWith('#')
          ) {
            continue; // Block javascript:, data:, etc.
          }
        }

        attrs.push(`${attrName}="${escapeAttrValue(attrValue)}"`);
      }
    }

    const isSelfClosing = match.endsWith('/>') || tag === 'br';
    const attrStr = attrs.length > 0 ? ' ' + attrs.join(' ') : '';
    return isSelfClosing ? `<${tag}${attrStr} />` : `<${tag}${attrStr}>`;
  });

  return result;
}

/** Escape HTML attribute values to prevent injection via attribute context. */
function escapeAttrValue(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}
