"""Tests for ingestion.split_ids — deterministic document ID generation for split rulings.

Tests cover:
  - make_split_document_id() determinism (same inputs -> same output)
  - make_split_document_id() uniqueness (different indices -> different IDs)
  - make_split_document_id() format (valid UUID strings)
  - Backward compatibility (IDs match the original splitter.py implementation)
"""

from __future__ import annotations

import uuid

from ingestion.split_ids import make_split_document_id


class TestMakeSplitDocumentId:
    """Tests for make_split_document_id()."""

    def test_deterministic(self) -> None:
        """Same inputs always produce the same ID."""
        doc_id = "aaaaaaaa-0000-0000-0000-000000000001"
        assert make_split_document_id(doc_id, 0) == make_split_document_id(doc_id, 0)
        assert make_split_document_id(doc_id, 1) == make_split_document_id(doc_id, 1)

    def test_different_indices_produce_different_ids(self) -> None:
        """Different split indices produce different IDs."""
        doc_id = "aaaaaaaa-0000-0000-0000-000000000001"
        id_0 = make_split_document_id(doc_id, 0)
        id_1 = make_split_document_id(doc_id, 1)
        id_2 = make_split_document_id(doc_id, 2)
        assert id_0 != id_1
        assert id_1 != id_2
        assert id_0 != id_2

    def test_different_documents_produce_different_ids(self) -> None:
        """Same index but different document IDs produce different results."""
        doc_a = "aaaaaaaa-0000-0000-0000-000000000001"
        doc_b = "bbbbbbbb-0000-0000-0000-000000000002"
        assert make_split_document_id(doc_a, 0) != make_split_document_id(doc_b, 0)

    def test_returns_valid_uuid(self) -> None:
        """Returned value is a valid UUID string."""
        doc_id = "aaaaaaaa-0000-0000-0000-000000000001"
        result = make_split_document_id(doc_id, 0)
        # Should not raise
        parsed = uuid.UUID(result)
        assert str(parsed) == result

    def test_backward_compatibility(self) -> None:
        """IDs match the original splitter.py implementation.

        The UUID namespace and format string are identical to the removed
        splitter.py module, ensuring existing split document IDs in the
        database remain valid after the migration.
        """
        # These expected values were generated by the original splitter.py
        # make_split_document_id function before removal.
        namespace = uuid.UUID("a3f1b2c4-d5e6-7890-abcd-ef1234567890")
        doc_id = "aaaaaaaa-0000-0000-0000-000000000001"

        expected_0 = str(uuid.uuid5(namespace, f"{doc_id}:0"))
        expected_1 = str(uuid.uuid5(namespace, f"{doc_id}:1"))

        assert make_split_document_id(doc_id, 0) == expected_0
        assert make_split_document_id(doc_id, 1) == expected_1
