"""Tests for ingestion.split_ids — deterministic document ID generation for split rulings.

Tests cover:
  - make_split_document_id() determinism (same inputs -> same output)
  - make_split_document_id() uniqueness (different indices -> different IDs)
  - make_split_document_id() format (valid UUID strings)
  - Backward compatibility (IDs match the original splitter.py implementation)
  - is_split_child_id() detection of split-child vs original document IDs
"""

from __future__ import annotations

import uuid

from ingestion.split_ids import (
    derive_parent_document_id,
    is_split_child_id,
    make_split_document_id,
)


class TestMakeSplitDocumentId:
    """Tests for make_split_document_id()."""

    def test_deterministic(self) -> None:
        """Same inputs always produce the same ID."""
        doc_id = "aaaaaaaa-0000-0000-0000-000000000001"
        assert make_split_document_id(doc_id, 0) == make_split_document_id(doc_id, 0)
        assert make_split_document_id(doc_id, 1) == make_split_document_id(doc_id, 1)

    def test_different_indices_produce_different_ids(self) -> None:
        """Different split indices produce different IDs."""
        doc_id = "aaaaaaaa-0000-0000-0000-000000000001"
        id_0 = make_split_document_id(doc_id, 0)
        id_1 = make_split_document_id(doc_id, 1)
        id_2 = make_split_document_id(doc_id, 2)
        assert id_0 != id_1
        assert id_1 != id_2
        assert id_0 != id_2

    def test_different_documents_produce_different_ids(self) -> None:
        """Same index but different document IDs produce different results."""
        doc_a = "aaaaaaaa-0000-0000-0000-000000000001"
        doc_b = "bbbbbbbb-0000-0000-0000-000000000002"
        assert make_split_document_id(doc_a, 0) != make_split_document_id(doc_b, 0)

    def test_returns_valid_uuid(self) -> None:
        """Returned value is a valid UUID string."""
        doc_id = "aaaaaaaa-0000-0000-0000-000000000001"
        result = make_split_document_id(doc_id, 0)
        # Should not raise
        parsed = uuid.UUID(result)
        assert str(parsed) == result

    def test_backward_compatibility(self) -> None:
        """IDs match the original splitter.py implementation.

        The UUID namespace and format string are identical to the removed
        splitter.py module, ensuring existing split document IDs in the
        database remain valid after the migration.
        """
        # These expected values were generated by the original splitter.py
        # make_split_document_id function before removal.
        namespace = uuid.UUID("a3f1b2c4-d5e6-7890-abcd-ef1234567890")
        doc_id = "aaaaaaaa-0000-0000-0000-000000000001"

        expected_0 = str(uuid.uuid5(namespace, f"{doc_id}:0"))
        expected_1 = str(uuid.uuid5(namespace, f"{doc_id}:1"))

        assert make_split_document_id(doc_id, 0) == expected_0
        assert make_split_document_id(doc_id, 1) == expected_1


class TestIsSplitChildId:
    """Tests for is_split_child_id()."""

    def test_detects_split_child_ids(self) -> None:
        """IDs generated by make_split_document_id are detected as split children."""
        parent_id = str(uuid.uuid4())
        child_0 = make_split_document_id(parent_id, 0)
        child_1 = make_split_document_id(parent_id, 1)
        assert is_split_child_id(child_0) is True
        assert is_split_child_id(child_1) is True

    def test_rejects_uuid4_ids(self) -> None:
        """Regular UUID v4 IDs (from scrapers) are not split children."""
        regular_id = str(uuid.uuid4())
        assert is_split_child_id(regular_id) is False

    def test_rejects_uuid1_ids(self) -> None:
        """UUID v1 IDs are not split children."""
        v1_id = str(uuid.uuid1())
        assert is_split_child_id(v1_id) is False

    def test_handles_invalid_uuid_strings(self) -> None:
        """Non-UUID strings return False instead of raising."""
        assert is_split_child_id("not-a-uuid") is False
        assert is_split_child_id("") is False
        assert is_split_child_id("12345") is False

    def test_handles_none_like_values(self) -> None:
        """Edge cases with None-ish values return False."""
        # Passing something that's technically a string but not a UUID
        assert is_split_child_id("00000000-0000-0000-0000-000000000000") is False

    def test_consistent_with_make_split_document_id(self) -> None:
        """Every ID from make_split_document_id is detected by is_split_child_id.

        Exercises multiple parent IDs and split indices to ensure the
        detection is robust across the full range of possible inputs.
        """
        for _ in range(10):
            parent_id = str(uuid.uuid4())
            for idx in range(5):
                child_id = make_split_document_id(parent_id, idx)
                assert is_split_child_id(child_id) is True, (
                    f"is_split_child_id failed for child_id={child_id} "
                    f"(parent={parent_id}, idx={idx})"
                )

    def test_scraper_v5_id_with_content_hash_is_parent(self) -> None:
        """Scraper-generated UUID v5 IDs (from uuid5(NAMESPACE_URL, content_hash))
        are NOT split children when content_hash is supplied.

        This is the #2367 regression: since #302, scraper IDs are derived via
        uuid5(NAMESPACE_URL, content_hash).  Both scraper IDs and split-child
        IDs are UUID v5, so a pure version-check mis-classifies scraper IDs
        as split children.  The content_hash parameter fixes this.
        """
        content_hash = "a" * 64  # fake sha256
        scraper_id = derive_parent_document_id(content_hash)
        # Without content_hash (legacy path): v5 → misclassified as split child.
        assert is_split_child_id(scraper_id) is True
        # With content_hash: recognized as the parent.
        assert is_split_child_id(scraper_id, content_hash) is False

    def test_split_child_with_content_hash_still_detected(self) -> None:
        """Split-child IDs are still detected as split children when the
        parent's content_hash is supplied (they don't match the parent-style
        derivation)."""
        content_hash = "b" * 64
        parent_id = derive_parent_document_id(content_hash)
        child = make_split_document_id(parent_id, 0)
        assert is_split_child_id(child, content_hash) is True

    def test_content_hash_none_preserves_legacy_behavior(self) -> None:
        """When content_hash is None, falls back to the UUID-version check."""
        content_hash = "c" * 64
        scraper_id = derive_parent_document_id(content_hash)
        assert is_split_child_id(scraper_id, None) is True
        assert is_split_child_id(scraper_id) is True  # default arg


class TestDeriveParentDocumentId:
    """Tests for derive_parent_document_id()."""

    def test_deterministic(self) -> None:
        """Same content hash always produces the same ID."""
        content_hash = "d" * 64
        assert derive_parent_document_id(content_hash) == derive_parent_document_id(content_hash)

    def test_matches_base_scraper_derivation(self) -> None:
        """Matches the exact UUID derivation used by BaseScraper._process_document."""
        content_hash = "e" * 64
        expected = str(uuid.uuid5(uuid.NAMESPACE_URL, content_hash))
        assert derive_parent_document_id(content_hash) == expected

    def test_different_hashes_produce_different_ids(self) -> None:
        """Different content hashes produce different IDs."""
        assert derive_parent_document_id("a" * 64) != derive_parent_document_id("b" * 64)
