"""Trend storage and analysis for data quality metrics.

Stores data quality check results as JSON snapshots in S3 and provides
trend detection and weekly summary generation.

S3 path convention:
    s3://<bucket>/data-quality/<YYYY-MM-DD>/<HH>.json

Each snapshot contains a timestamp and per-county metrics (ruling counts
and field completeness percentages).

This module is designed to be imported by ``data-quality-check.py`` and
tested independently with mocked S3 clients.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Any

import boto3
from botocore.exceptions import ClientError

logger = logging.getLogger(__name__)

# S3 defaults
DEFAULT_BUCKET = "judgemind-assets-dev"
S3_PREFIX = "data-quality"

# Trend detection thresholds
TREND_WINDOW_DAYS = 7
TREND_DECLINE_THRESHOLD = 5.0  # Percentage-point decline week-over-week to flag


@dataclass
class Snapshot:
    """A single data quality check snapshot."""

    timestamp: str  # ISO-8601
    county_metrics: dict[str, dict[str, Any]]
    alerts: list[dict[str, Any]]


@dataclass
class TrendAlert:
    """An alert generated by trend analysis."""

    county: str
    metric: str
    severity: str  # always p2 for trends
    current_avg: float
    prior_avg: float
    change_pct: float
    message: str


def store_snapshot(
    snapshot: Snapshot,
    *,
    bucket: str = DEFAULT_BUCKET,
    s3_client: Any | None = None,
) -> str:
    """Store a data quality snapshot to S3.

    Args:
        snapshot: The snapshot data to store.
        bucket: S3 bucket name.
        s3_client: Optional pre-configured S3 client (for testing).

    Returns:
        The S3 key where the snapshot was stored.
    """
    if s3_client is None:
        s3_client = boto3.client("s3")

    ts = datetime.fromisoformat(snapshot.timestamp)
    key = f"{S3_PREFIX}/{ts.strftime('%Y-%m-%d')}/{ts.strftime('%H')}.json"

    body = json.dumps(
        {
            "timestamp": snapshot.timestamp,
            "county_metrics": snapshot.county_metrics,
            "alerts": snapshot.alerts,
        },
        indent=2,
        default=str,
    )

    s3_client.put_object(
        Bucket=bucket,
        Key=key,
        Body=body.encode("utf-8"),
        ContentType="application/json",
    )

    logger.info("Stored snapshot to s3://%s/%s", bucket, key)
    return key


def load_snapshots(
    *,
    days: int = TREND_WINDOW_DAYS,
    now: datetime | None = None,
    bucket: str = DEFAULT_BUCKET,
    s3_client: Any | None = None,
) -> list[Snapshot]:
    """Load recent data quality snapshots from S3.

    Scans the last ``days`` worth of date-prefixed keys and returns all
    snapshots found, sorted by timestamp ascending.

    Args:
        days: Number of days of history to load.
        now: Override current time (for testing).
        bucket: S3 bucket name.
        s3_client: Optional pre-configured S3 client (for testing).

    Returns:
        List of Snapshot objects sorted by timestamp ascending.
    """
    if s3_client is None:
        s3_client = boto3.client("s3")
    if now is None:
        now = datetime.now(UTC)

    snapshots: list[Snapshot] = []

    for day_offset in range(days):
        date = now - timedelta(days=day_offset)
        prefix = f"{S3_PREFIX}/{date.strftime('%Y-%m-%d')}/"

        try:
            response = s3_client.list_objects_v2(Bucket=bucket, Prefix=prefix)
        except ClientError as e:
            logger.warning("Failed to list S3 objects at %s: %s", prefix, e)
            continue

        for obj in response.get("Contents", []):
            try:
                result = s3_client.get_object(Bucket=bucket, Key=obj["Key"])
                data = json.loads(result["Body"].read().decode("utf-8"))
                snapshots.append(
                    Snapshot(
                        timestamp=data["timestamp"],
                        county_metrics=data.get("county_metrics", {}),
                        alerts=data.get("alerts", []),
                    )
                )
            except (ClientError, json.JSONDecodeError, KeyError) as e:
                logger.warning("Failed to load snapshot %s: %s", obj["Key"], e)
                continue

    snapshots.sort(key=lambda s: s.timestamp)
    return snapshots


def detect_trends(
    snapshots: list[Snapshot],
    *,
    now: datetime | None = None,
) -> list[TrendAlert]:
    """Detect sustained downward trends in county metrics.

    Compares the most recent half of the window (last 3.5 days) against the
    prior half (days 3.5-7) to identify counties with declining metrics.

    Only generates alerts when the decline exceeds TREND_DECLINE_THRESHOLD
    percentage points. All trend alerts are severity p2.

    Args:
        snapshots: List of historical snapshots (sorted by timestamp ascending).
        now: Override current time (for testing).

    Returns:
        List of TrendAlert objects for counties with sustained declines.
    """
    if now is None:
        now = datetime.now(UTC)

    if len(snapshots) < 2:
        return []

    # Split snapshots into recent half and prior half
    midpoint = now - timedelta(days=TREND_WINDOW_DAYS / 2)
    midpoint_str = midpoint.isoformat()

    recent_snapshots = [s for s in snapshots if s.timestamp >= midpoint_str]
    prior_snapshots = [s for s in snapshots if s.timestamp < midpoint_str]

    if not recent_snapshots or not prior_snapshots:
        return []

    alerts: list[TrendAlert] = []

    # Collect all counties seen in any snapshot
    all_counties: set[str] = set()
    for snap in snapshots:
        all_counties.update(snap.county_metrics.keys())

    for county in sorted(all_counties):
        # Check field completeness trends
        _check_field_trends(county, recent_snapshots, prior_snapshots, alerts)

        # Check ruling count trends
        _check_ruling_count_trends(county, recent_snapshots, prior_snapshots, alerts)

    return alerts


def _avg_field_completeness(
    county: str,
    snapshots: list[Snapshot],
    field: str,
) -> float | None:
    """Compute average field completeness for a county across snapshots.

    Args:
        county: County name.
        snapshots: Snapshots to average over.
        field: Field name in field_completeness dict.

    Returns:
        Average percentage, or None if no data.
    """
    values: list[float] = []
    for snap in snapshots:
        metrics = snap.county_metrics.get(county, {})
        fc = metrics.get("field_completeness", {})
        if field in fc:
            values.append(fc[field])
    return sum(values) / len(values) if values else None


def _avg_ruling_count(
    county: str,
    snapshots: list[Snapshot],
) -> float | None:
    """Compute average ruling count for a county across snapshots.

    Args:
        county: County name.
        snapshots: Snapshots to average over.

    Returns:
        Average count, or None if no data.
    """
    values: list[float] = []
    for snap in snapshots:
        metrics = snap.county_metrics.get(county, {})
        count = metrics.get("ruling_count_24h")
        if count is not None:
            values.append(float(count))
    return sum(values) / len(values) if values else None


def _check_field_trends(
    county: str,
    recent: list[Snapshot],
    prior: list[Snapshot],
    alerts: list[TrendAlert],
) -> None:
    """Check field completeness trends for a county.

    Args:
        county: County name.
        recent: Recent snapshots (most recent half of window).
        prior: Prior snapshots (older half of window).
        alerts: List to append alerts to.
    """
    # Get all field names from any snapshot for this county
    fields: set[str] = set()
    for snap in recent + prior:
        metrics = snap.county_metrics.get(county, {})
        fields.update(metrics.get("field_completeness", {}).keys())

    for field in sorted(fields):
        recent_avg = _avg_field_completeness(county, recent, field)
        prior_avg = _avg_field_completeness(county, prior, field)

        if recent_avg is None or prior_avg is None:
            continue

        # Only flag if prior average was meaningful (>0)
        if prior_avg == 0.0:
            continue

        decline = prior_avg - recent_avg
        if decline > TREND_DECLINE_THRESHOLD:
            alerts.append(
                TrendAlert(
                    county=county,
                    metric=f"field_trend:{field}",
                    severity="p2",
                    current_avg=round(recent_avg, 1),
                    prior_avg=round(prior_avg, 1),
                    change_pct=round(-decline, 1),
                    message=(
                        f"{county}: {field} completeness trending down "
                        f"({prior_avg:.1f}% -> {recent_avg:.1f}%, "
                        f"{decline:.1f}pp decline over {TREND_WINDOW_DAYS}d)"
                    ),
                )
            )


def _check_ruling_count_trends(
    county: str,
    recent: list[Snapshot],
    prior: list[Snapshot],
    alerts: list[TrendAlert],
) -> None:
    """Check ruling count trends for a county.

    Args:
        county: County name.
        recent: Recent snapshots (most recent half of window).
        prior: Prior snapshots (older half of window).
        alerts: List to append alerts to.
    """
    recent_avg = _avg_ruling_count(county, recent)
    prior_avg = _avg_ruling_count(county, prior)

    if recent_avg is None or prior_avg is None:
        return

    # Only flag if prior average was meaningful (>0)
    if prior_avg == 0.0:
        return

    decline_pct = ((prior_avg - recent_avg) / prior_avg) * 100
    if decline_pct > TREND_DECLINE_THRESHOLD:
        alerts.append(
            TrendAlert(
                county=county,
                metric="ruling_count_trend",
                severity="p2",
                current_avg=round(recent_avg, 1),
                prior_avg=round(prior_avg, 1),
                change_pct=round(-decline_pct, 1),
                message=(
                    f"{county}: ruling count trending down "
                    f"({prior_avg:.1f}/day -> {recent_avg:.1f}/day, "
                    f"{decline_pct:.1f}% decline over {TREND_WINDOW_DAYS}d)"
                ),
            )
        )


def generate_weekly_summary(
    snapshots: list[Snapshot],
    *,
    now: datetime | None = None,
) -> str:
    """Generate a markdown weekly summary report.

    Args:
        snapshots: Historical snapshots to analyze.
        now: Override current time (for testing).

    Returns:
        Markdown-formatted weekly summary string.
    """
    if now is None:
        now = datetime.now(UTC)

    lines: list[str] = []
    lines.append(f"# Data Quality Weekly Summary — {now.strftime('%Y-%m-%d')}")
    lines.append("")

    if not snapshots:
        lines.append("No historical data available for the reporting period.")
        return "\n".join(lines)

    # Collect all counties
    all_counties: set[str] = set()
    for snap in snapshots:
        all_counties.update(snap.county_metrics.keys())

    if not all_counties:
        lines.append("No county metrics found in snapshots.")
        return "\n".join(lines)

    # Split into recent and prior halves for trend computation
    midpoint = now - timedelta(days=TREND_WINDOW_DAYS / 2)
    midpoint_str = midpoint.isoformat()
    recent = [s for s in snapshots if s.timestamp >= midpoint_str]
    prior = [s for s in snapshots if s.timestamp < midpoint_str]

    # --- Overall collection rate ---
    lines.append("## Overall Collection Rate")
    lines.append("")

    total_recent_rulings = 0.0
    total_prior_rulings = 0.0
    county_count = 0

    for county in sorted(all_counties):
        r_avg = _avg_ruling_count(county, recent)
        p_avg = _avg_ruling_count(county, prior)
        if r_avg is not None:
            total_recent_rulings += r_avg
            county_count += 1
        if p_avg is not None:
            total_prior_rulings += p_avg

    lines.append(f"- **Active counties:** {county_count}")
    lines.append(f"- **Average daily rulings (recent):** {total_recent_rulings:.0f}")
    if total_prior_rulings > 0:
        change = (
            (total_recent_rulings - total_prior_rulings) / total_prior_rulings
        ) * 100
        direction = "up" if change >= 0 else "down"
        lines.append(f"- **Week-over-week change:** {abs(change):.1f}% {direction}")
    lines.append("")

    # --- Field completeness trends ---
    lines.append("## Field Completeness Trends")
    lines.append("")
    lines.append("| County | Field | Prior Avg | Recent Avg | Trend |")
    lines.append("|--------|-------|-----------|------------|-------|")

    trend_rows: list[tuple[str, str, float, float, str]] = []
    for county in sorted(all_counties):
        fields: set[str] = set()
        for snap in snapshots:
            metrics = snap.county_metrics.get(county, {})
            fields.update(metrics.get("field_completeness", {}).keys())

        for field in sorted(fields):
            r_avg = _avg_field_completeness(county, recent, field)
            p_avg = _avg_field_completeness(county, prior, field)
            if r_avg is None:
                continue

            if p_avg is not None and p_avg > 0:
                diff = r_avg - p_avg
                if diff > 1.0:
                    trend = "improving"
                elif diff < -1.0:
                    trend = "declining"
                else:
                    trend = "stable"
                trend_rows.append((county, field, p_avg, r_avg, trend))
            elif r_avg is not None:
                trend_rows.append((county, field, 0.0, r_avg, "new"))

    for county, field, p_avg, r_avg, trend in trend_rows:
        lines.append(f"| {county} | {field} | {p_avg:.1f}% | {r_avg:.1f}% | {trend} |")

    if not trend_rows:
        lines.append("| (no field data available) | | | | |")
    lines.append("")

    # --- Downward trends ---
    trends = detect_trends(snapshots, now=now)
    lines.append("## Sustained Downward Trends")
    lines.append("")
    if trends:
        for t in trends:
            lines.append(f"- **{t.county}** ({t.metric}): {t.message}")
    else:
        lines.append("No sustained downward trends detected.")
    lines.append("")

    # --- Recent alerts ---
    lines.append("## Recent Alerts")
    lines.append("")
    # Gather alerts from the most recent snapshot
    if snapshots:
        latest = snapshots[-1]
        if latest.alerts:
            for alert_dict in latest.alerts:
                severity = alert_dict.get("severity", "?")
                message = alert_dict.get("message", str(alert_dict))
                marker = f"[{severity.upper()}]"
                lines.append(f"- {marker} {message}")
        else:
            lines.append("No active alerts in the most recent check.")
    lines.append("")

    lines.append(
        f"_Report generated {now.strftime('%Y-%m-%d %H:%M UTC')} "
        f"from {len(snapshots)} snapshots over {TREND_WINDOW_DAYS} days._"
    )

    return "\n".join(lines)
