#!/usr/bin/env bash
# Regenerate schema.sql from migrations.
#
# Creates a fresh database, applies all migrations (up sections only),
# then pg_dumps the result to schema.sql. This ensures schema.sql is
# always the authoritative, complete schema.
#
# Usage: scripts/regenerate_schema.sh
#
# Requires: Docker running with the postgres service from docker-compose.yml

set -euo pipefail

CONTAINER="judgemind-bootstrap-postgres-1"
TEMP_DB="judgemind_schema_gen"
SCHEMA_FILE="packages/api/src/data-access/schema.sql"
MIGRATIONS_DIR="packages/api/migrations"

echo "=== Regenerating $SCHEMA_FILE from migrations ==="

# Create a temporary database
docker exec "$CONTAINER" psql -U judgemind -d postgres -c "DROP DATABASE IF EXISTS $TEMP_DB" -q
docker exec "$CONTAINER" psql -U judgemind -d postgres -c "CREATE DATABASE $TEMP_DB OWNER judgemind" -q

# Apply all migrations (up sections only)
for f in $(ls "$MIGRATIONS_DIR"/*.sql | sort -t/ -k3 -V); do
    name=$(basename "$f")
    echo "  Applying $name ..."
    up_sql=$(sed '/^-- Down Migration/,$d' "$f")
    echo "$up_sql" | docker exec -i "$CONTAINER" psql -U judgemind -d "$TEMP_DB" -v ON_ERROR_STOP=1 -q 2>&1
done

# Dump the schema
echo "  Dumping schema..."
docker exec "$CONTAINER" pg_dump -U judgemind --schema-only --no-owner --no-privileges --no-tablespaces "$TEMP_DB" \
    | grep -v '^\\\(restrict\|allow\|unrestrict\)' \
    | grep -v '^-- Dumped from\|^-- Dumped by' \
    | sed '/^--$/{ N; /^--\n-- PostgreSQL database dump/,/^--$/d; }' \
    > "$SCHEMA_FILE"

# Add header
HEADER="-- Judgemind database schema (auto-generated).
-- DO NOT EDIT THIS FILE DIRECTLY.
-- To modify the schema, add a migration in packages/api/migrations/
-- then run: scripts/regenerate_schema.sh
--
-- Generated from migrations 1-$(ls "$MIGRATIONS_DIR"/*.sql | wc -l | tr -d ' ')
-- $(date -u '+%Y-%m-%d %H:%M UTC')
"
echo "$HEADER" | cat - "$SCHEMA_FILE" > "$SCHEMA_FILE.tmp"
mv "$SCHEMA_FILE.tmp" "$SCHEMA_FILE"

# Clean up
docker exec "$CONTAINER" psql -U judgemind -d postgres -c "DROP DATABASE $TEMP_DB" -q

echo "=== Done. Schema written to $SCHEMA_FILE ==="
