"""Hearing-date extractors must not fall through to ruling-body dates (#4682).

#4667: Santa Clara's hearing-date regex had an optional ``DATE:`` prefix and
was searched across the whole document.  When the header didn't match, it
silently returned the first long-form date in the ruling body (a date of
birth, a discovery service date) and every split ruling inherited it, so the
180-day plausibility rule dropped whole PDFs.

This module audits every California hearing-date extractor for the same
shape.  Each ``*_body_date_not_hearing_date`` test feeds body-only prose
(dates that are NOT hearing dates) with no recognisable header and asserts
the extractor returns ``None``.  Each ``*_header_date_wins`` test is the
positive control: with the header present, the header date is returned even
when a body date appears first.
"""

from __future__ import annotations

from datetime import date, datetime

import pytest
from bs4 import BeautifulSoup

from courts.ca.cc_tentatives import _cc_hearing_date_from_pdf
from courts.ca.fresno_tentatives import _fresno_hearing_date_from_text
from courts.ca.la_tentatives import _extract_header_fields
from courts.ca.oc_family_law_tentatives import _oc_fl_hearing_date_from_text
from courts.ca.oc_probate_tentatives import _probate_hearing_date_from_text
from courts.ca.riverside_tentatives import _riv_hearing_date_from_text
from courts.ca.sc_tentatives import parse_hearing_date as sc_parse_hearing_date
from courts.ca.sd_calendar import _parse_calendar_date
from courts.ca.sd_tentatives import parse_tentative_ruling
from courts.ca.ventura_tentatives import parse_event_datetime
from ingestion.extract import extract_hearing_date

pytestmark = pytest.mark.regression

# Body prose modelled on the real #4667 / #4682 false positives: a claimant's
# date of birth, discovery service dates, trust formation dates, and the SF
# Unified Family Court boilerplate ("effective January 2, 2024").
BODY_ONLY = (
    "Plaintiff, date of birth (September 13, 1972), alleges that defendant\n"
    "served responses on 03/04/2021.  The Smith Family Trust dated\n"
    "October 17 1988 is the petitioner.  Remote appearances can be made\n"
    "utilizing the ZOOM platform, effective January 2, 2024.\n"
    "On or about November 30, 2022 the parties entered into an agreement.\n"
    "The motion to compel is GRANTED.\n"
)


def _to_date(value: object) -> date | None:
    if value is None:
        return None
    if isinstance(value, datetime):
        return value.date()
    assert isinstance(value, date)
    return value


# ---------------------------------------------------------------------------
# ingestion.extract.extract_hearing_date — shared fallback used by the worker
# (regex_fallback phase), San Bernardino's parse_document, rebuild_db.py
# (HTML events) and reingest_from_s3.py.
# ---------------------------------------------------------------------------


class TestExtractHearingDateFallback:
    def test_extract_hearing_date_body_date_not_hearing_date(self) -> None:
        assert extract_hearing_date(BODY_ONLY) is None

    def test_extract_hearing_date_generated_comment_body_date_not_hearing_date(self) -> None:
        """SD HTML carries a generator timestamp — not a hearing date."""
        html = "<head>\n<!-- Generated by San Diego Superior Court 9/23/2026 -->\n</head>"
        assert extract_hearing_date(html) is None

    @pytest.mark.parametrize(
        ("header", "expected"),
        [
            ("Hearing Date: May 28, 2026", date(2026, 5, 28)),
            ("<b> Hearing Date: </b>  August 4, 2026", date(2026, 8, 4)),
            ("Hearing Date and Time: September 24, 2026", date(2026, 9, 24)),
            ("HEARING DATE: 09/23/2026", date(2026, 9, 23)),
            ("Tentative Rulings for March 9, 2026", date(2026, 3, 9)),
            ("TENTATIVE RULING(S) FOR February 11, 2026", date(2026, 2, 11)),
            ("TENTATIVE RULING FOR MARCH 3 & 4, 2026", date(2026, 3, 3)),
            ("Tentative Rulings\nSeptember 28, 2026", date(2026, 9, 28)),
            ("No Tentative Rulings March 2, 2026", date(2026, 3, 2)),
            ("COURT CALENDAR FOR AUGUST 13, 2026", date(2026, 8, 13)),
            ("CIVIL CALENDAR For Friday, 03/13/2026", date(2026, 3, 13)),
            ("HON. YOLANDA V. TORRES\nDate: September 28, 2026", date(2026, 9, 28)),
            ("N14\nDate: Monday, September 28, 2026", date(2026, 9, 28)),
            ("Date: 03/04/26\nCourtroom B", date(2026, 3, 4)),
        ],
    )
    def test_extract_hearing_date_header_date_wins(self, header: str, expected: date) -> None:
        # Header after body prose: the labelled date must still win over the
        # earlier body dates.
        assert extract_hearing_date(BODY_ONLY + header + "\n") == expected

    def test_extract_hearing_date_filing_date_label_body_date_not_hearing_date(self) -> None:
        """'Filing Date:' / 'Service Date:' are not hearing-date labels."""
        text = "Complaint Filing Date: 01/05/2020\nService Date: March 3, 2021\n"
        assert extract_hearing_date(text) is None


# ---------------------------------------------------------------------------
# Per-scraper extractors
# ---------------------------------------------------------------------------


def test_oc_family_law_body_date_not_hearing_date() -> None:
    assert _oc_fl_hearing_date_from_text(BODY_ONLY) is None


def test_oc_family_law_empty_date_label_body_date_not_hearing_date() -> None:
    """Placeholder PDFs print 'Date:' with no value — don't grab a body date."""
    text = "TENTATIVE RULINGS\nDate:\n# Case Name TENTATIVE RULING\n" + BODY_ONLY
    assert _oc_fl_hearing_date_from_text(text) is None


def test_oc_family_law_header_date_wins() -> None:
    text = "TENTATIVE RULINGS\nDate: December 5, 2025\n" + BODY_ONLY
    assert _oc_fl_hearing_date_from_text(text) == datetime(2025, 12, 5)


def test_riverside_body_date_not_hearing_date() -> None:
    assert _riv_hearing_date_from_text(BODY_ONLY) is None


def test_riverside_header_date_wins() -> None:
    text = "Tentative Rulings for March 2, 2026\n" + BODY_ONLY
    assert _riv_hearing_date_from_text(text) == datetime(2026, 3, 2)


def test_fresno_body_date_not_hearing_date() -> None:
    assert _fresno_hearing_date_from_text(BODY_ONLY) is None


def test_fresno_header_date_wins() -> None:
    text = BODY_ONLY + "Hearing Date: March 10, 2026 (Dept. 403)\n"
    assert _fresno_hearing_date_from_text(text) == datetime(2026, 3, 10)


def test_la_body_date_not_hearing_date() -> None:
    soup = BeautifulSoup(f"<div id='speechSynthesis'><p>{BODY_ONLY}</p></div>", "lxml")
    assert _extract_header_fields(soup).hearing_date is None


def test_la_header_date_wins() -> None:
    html = (
        "<div id='speechSynthesis'><p>" + BODY_ONLY + "</p>"
        "<b>Case Number:</b> 24NNCV02551 <b>Hearing Date:</b> March 2, 2026 "
        "<b>Dept:</b> 3</div>"
    )
    soup = BeautifulSoup(html, "lxml")
    assert _extract_header_fields(soup).hearing_date == datetime(2026, 3, 2)


def test_oc_probate_body_date_not_hearing_date() -> None:
    assert _probate_hearing_date_from_text(BODY_ONLY) is None


def test_oc_probate_header_date_wins() -> None:
    text = BODY_ONLY + "Date: 03/16/2026\n"
    assert _to_date(_probate_hearing_date_from_text(text)) == date(2026, 3, 16)


def test_contra_costa_body_date_not_hearing_date() -> None:
    assert _cc_hearing_date_from_pdf(BODY_ONLY) is None


@pytest.mark.parametrize(
    ("header", "expected"),
    [
        ("HEARING DATE: 03/11/2026", datetime(2026, 3, 11)),
        ("COURT CALENDAR FOR MARCH 16, 2026", datetime(2026, 3, 16)),
    ],
)
def test_contra_costa_header_date_wins(header: str, expected: datetime) -> None:
    assert _cc_hearing_date_from_pdf(BODY_ONLY + header) == expected


def _sd_roa(desc_html: str) -> BeautifulSoup:
    return BeautifulSoup(
        "<table class='roa-table'><tbody><tr><td>1</td><td>Tentative Ruling</td>"
        f"<td>{desc_html}<div class='ruling-content'><p>{BODY_ONLY}</p></div></td>"
        "</tr></tbody></table>",
        "lxml",
    )


def test_san_diego_tentatives_body_date_not_hearing_date() -> None:
    _, hearing_date = parse_tentative_ruling(_sd_roa(""))
    assert hearing_date is None


def test_san_diego_tentatives_header_date_wins() -> None:
    _, hearing_date = parse_tentative_ruling(_sd_roa("Hearing Date: March 13, 2026"))
    assert hearing_date == datetime(2026, 3, 13)


def test_san_diego_calendar_body_date_not_hearing_date() -> None:
    html = f"<html><body><h1>CIVIL CALENDAR</h1><p>{BODY_ONLY}</p></body></html>"
    assert _parse_calendar_date(html) is None


def test_san_diego_calendar_header_date_wins() -> None:
    html = f"<h1>CIVIL CALENDAR For Friday, 03/13/2026</h1><p>{BODY_ONLY}</p>"
    assert _parse_calendar_date(html) == datetime(2026, 3, 13)


def test_ventura_body_date_not_hearing_date() -> None:
    """Ventura reads a structured event-datetime cell; a bare date isn't one."""
    assert parse_event_datetime(BODY_ONLY) is None


def test_ventura_header_date_wins() -> None:
    assert parse_event_datetime("09/24/2026 8:30 AM") == datetime(2026, 9, 24, 8, 30)


def test_santa_clara_body_date_not_hearing_date() -> None:
    """Fixed by #4667 — kept here so the audit covers every CA extractor."""
    assert sc_parse_hearing_date(BODY_ONLY) is None
